NAME = libft.a

SOURCE = \
		ft_isalpha.c\
		ft_isdigit.c\
		ft_isalnum.c\
		ft_isascii.c\
		ft_isprint.c\
		ft_strlen.c\
		ft_memset.c\
		ft_bzero.c\
		ft_memcpy.c\
		ft_memmove.c\
		ft_strlcpy.c\
		ft_strlcat.c\
		ft_toupper.c\
		ft_tolower.c\
		ft_strchr.c\
		ft_strrchr.c\
		ft_strncmp.c\
		ft_memchr.c\
		ft_memcmp.c\
		ft_strnstr.c\
		ft_atoi.c\
		ft_calloc.c\
		ft_strdup.c\
		ft_substr.c\
		ft_strjoin.c\
		ft_strtrim.c
CC = cc -Wall -Wextra -Werror
all: $(NAME)
$(NAME):$(SOURCE:.c=.o)
	ar rcs $(NAME) $(SOURCE:.c=.o)
$(SOURCE:.c=.o):$(SOURCE)
	$(CC) -c $(SOURCE)
clean:
	rm -f $(SOURCE:.c=.o)
fclean:clean
	rm -f $(NAME)
re:fclean all
.PHONY:all clean fclean re